/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tugaspert12;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Date;                    // ✅ tambahan
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;  // ✅ tambahan
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author RAISSA
 */

public class GUIMainClass12 extends javax.swing.JFrame {
    
    private DefaultTableModel modelDepo;
    private DefaultTableModel modelPerawatan;
    
    private static final EntityManagerFactory emf =
            Persistence.createEntityManagerFactory("TugasPert12PU");
    public GUIMainClass12() {
        initComponents();
        setTitle("Depo Kereta Surabaya Pasarturi");
        loadTables(); // load data saat GUI dijalankan
    }

    private void loadTables() {
        EntityManager em = emf.createEntityManager();

        // Tabel Depo
        List<Depokeretasbi> depoList = em.createQuery("SELECT d FROM Depokeretasbi d", Depokeretasbi.class).getResultList();
        modelDepo = (DefaultTableModel) jTable1.getModel();
        modelDepo.setRowCount(0);
        for (Depokeretasbi d : depoList) {
            modelDepo.addRow(new Object[]{
                d.getIdArmada(),
                d.getNomorArmada(),
                d.getJenisArmada(),
                d.getTanggalMulaiDinas()
            });
        }

        // Tabel Perawatan
        List<PerawatanKereta> perawatanList = em.createQuery("SELECT p FROM PerawatanKereta p", PerawatanKereta.class).getResultList();
        modelPerawatan = (DefaultTableModel) jTable2.getModel();
        modelPerawatan.setRowCount(0);
        for (PerawatanKereta p : perawatanList) {
            modelPerawatan.addRow(new Object[]{
                p.getIdPerawatan(),
                p.getIdArmada().getNomorArmada(),
                p.getJenisPerawatan(),
                p.getTanggalPerawatan(),
                p.getKeterangan()
            });
        }
        em.close();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 759, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Armada", jPanel1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 754, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 754, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("tab1", jPanel2);

        jTabbedPane1.addTab("Data Perawatan", jTabbedPane2);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel1.setText("DEPO KERETA SURABAYA PASARTURI");

        jButton1.setText("Insert");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Quit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Unggah");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Cetak");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Download CSV");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)
                        .addGap(83, 83, 83)
                        .addComponent(jButton7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton6)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton6)
                    .addComponent(jButton7))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // Input Depo
            String nomor = JOptionPane.showInputDialog(this, "Masukkan Nomor Armada:");
            if (nomor == null || nomor.isEmpty()) return;
            String jenis = JOptionPane.showInputDialog(this, "Masukkan Jenis Armada:");
            if (jenis == null || jenis.isEmpty()) return;
            String tglDepo = JOptionPane.showInputDialog(this, "Masukkan Tanggal Mulai Dinas (YYYY-MM-DD):");
            if (tglDepo == null || tglDepo.isEmpty()) return;
            // Input Perawatan
            String tglPerawatan = JOptionPane.showInputDialog(this, "Masukkan Tanggal Perawatan (YYYY-MM-DD):");
            if (tglPerawatan == null || tglPerawatan.isEmpty()) return;
            String jenisPerawatan = JOptionPane.showInputDialog(this, "Masukkan Jenis Perawatan:");
            if (jenisPerawatan == null || jenisPerawatan.isEmpty()) return;
            String keterangan = JOptionPane.showInputDialog(this, "Masukkan Keterangan Perawatan:");
            if (keterangan == null) return;
            EntityManagerFactory emf = Persistence.createEntityManagerFactory("TugasPert12PU");
            EntityManager em = emf.createEntityManager();
            em.getTransaction().begin();
            Depokeretasbi depo = new Depokeretasbi();
            depo.setNomorArmada(nomor);
            depo.setJenisArmada(jenis);
            depo.setTanggalMulaiDinas(Date.valueOf(tglDepo));
            em.persist(depo);
            em.flush(); // memastikan id_armada tersedia
            PerawatanKereta perawatan = new PerawatanKereta();
            perawatan.setIdArmada(depo);
            perawatan.setTanggalPerawatan(Date.valueOf(tglPerawatan));
            perawatan.setJenisPerawatan(jenisPerawatan);
            perawatan.setKeterangan(keterangan);
            em.persist(perawatan);
            em.getTransaction().commit();
            em.close();
            emf.close();
            JOptionPane.showMessageDialog(this, "✅ Data berhasil disimpan!");
            loadTables(); // reload tabel
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "❌ Gagal menyimpan data: " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Pilih tabel untuk update
        String[] options = {"Depo", "Perawatan"};
        int choice = JOptionPane.showOptionDialog(this, "Pilih tabel yang ingin diupdate:", "Update",
                JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE, null, options, options[0]);
        if (choice == -1) return;
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("TugasPert12PU");
        EntityManager em = emf.createEntityManager();
        try {
            em.getTransaction().begin();
            if (choice == 0) { // Depo
                int row = jTable1.getSelectedRow();
                if (row == -1) {
                    JOptionPane.showMessageDialog(this, "⚠️ Pilih baris Depo yang ingin diupdate!");
                    return;
                }
                int idDepo = Integer.parseInt(jTable1.getValueAt(row, 0).toString());
                Depokeretasbi depo = em.find(Depokeretasbi.class, idDepo);
                if (depo == null) {
                    JOptionPane.showMessageDialog(this, "⚠️ Data tidak ditemukan!");
                    return;
                }
                String nomor = JOptionPane.showInputDialog(this, "Nomor Armada:", depo.getNomorArmada());
                String jenis = JOptionPane.showInputDialog(this, "Jenis Armada:", depo.getJenisArmada());
                String tgl = JOptionPane.showInputDialog(this, "Tanggal Mulai Dinas (YYYY-MM-DD):", depo.getTanggalMulaiDinas().toString());
                depo.setNomorArmada(nomor);
                depo.setJenisArmada(jenis);
                depo.setTanggalMulaiDinas(Date.valueOf(tgl));
                em.merge(depo);
            } else { // Perawatan
                int row = jTable2.getSelectedRow();
                if (row == -1) {
                    JOptionPane.showMessageDialog(this, "⚠️ Pilih baris Perawatan yang ingin diupdate!");
                    return;
                }
                int idPerawatan = Integer.parseInt(jTable2.getValueAt(row, 0).toString());
                PerawatanKereta perawatan = em.find(PerawatanKereta.class, idPerawatan);
                if (perawatan == null) {
                    JOptionPane.showMessageDialog(this, "⚠️ Data tidak ditemukan!");
                    return;
                }
                String tgl = JOptionPane.showInputDialog(this, "Tanggal Perawatan (YYYY-MM-DD):", perawatan.getTanggalPerawatan().toString());
                String jenis = JOptionPane.showInputDialog(this, "Jenis Perawatan:", perawatan.getJenisPerawatan());
                String ket = JOptionPane.showInputDialog(this, "Keterangan:", perawatan.getKeterangan());
                perawatan.setTanggalPerawatan(Date.valueOf(tgl));
                perawatan.setJenisPerawatan(jenis);
                perawatan.setKeterangan(ket);
                em.merge(perawatan);
            }
            em.getTransaction().commit();
            JOptionPane.showMessageDialog(this, "✅ Data berhasil diperbarui!");
            loadTables();
        } catch (Exception e) {
            if (em.getTransaction().isActive()) em.getTransaction().rollback();
            JOptionPane.showMessageDialog(this, "❌ Gagal update: " + e.getMessage());
            e.printStackTrace();
        } finally {
            em.close();
            emf.close();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String[] options = {"Depo", "Perawatan"};
        int choice = JOptionPane.showOptionDialog(this, "Pilih tabel yang ingin dihapus:", "Delete",
                JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE, null, options, options[0]);
        if (choice == -1) return;

        EntityManagerFactory emf = Persistence.createEntityManagerFactory("TugasPert12PU");
        EntityManager em = emf.createEntityManager();

        try {
            em.getTransaction().begin();

            if (choice == 0) { // Depo
                int row = jTable1.getSelectedRow();
                if (row == -1) {
                    JOptionPane.showMessageDialog(this, "⚠️ Pilih baris Depo yang ingin dihapus!");
                    return;
                }
                int idDepo = Integer.parseInt(jTable1.getValueAt(row, 0).toString());
                Depokeretasbi depo = em.find(Depokeretasbi.class, idDepo);
                if (depo != null) {
                    // hapus perawatan terkait dulu
                    List<PerawatanKereta> perawatanList = em.createQuery("SELECT p FROM PerawatanKereta p WHERE p.idArmada.idArmada=:id", PerawatanKereta.class)
                            .setParameter("id", idDepo)
                            .getResultList();
                    for (PerawatanKereta p : perawatanList) {
                        em.remove(p);
                    }
                    em.remove(depo);
                }

            } else { // Perawatan
                int row = jTable2.getSelectedRow();
                if (row == -1) {
                    JOptionPane.showMessageDialog(this, "⚠️ Pilih baris Perawatan yang ingin dihapus!");
                    return;
                }
                int idPerawatan = Integer.parseInt(jTable2.getValueAt(row, 0).toString());
                PerawatanKereta perawatan = em.find(PerawatanKereta.class, idPerawatan);
                if (perawatan != null) em.remove(perawatan);
            }

            em.getTransaction().commit();
            JOptionPane.showMessageDialog(this, "✅ Data berhasil dihapus!");
            loadTables();

        } catch (Exception e) {
            if (em.getTransaction().isActive()) em.getTransaction().rollback();
            JOptionPane.showMessageDialog(this, "❌ Gagal hapus: " + e.getMessage());
            e.printStackTrace();
        } finally {
            em.close();
            emf.close();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int confirm = JOptionPane.showConfirmDialog(this, "Yakin ingin keluar?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        JFileChooser chooser = new JFileChooser();
    if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
        File file = chooser.getSelectedFile();
        try (BufferedReader br = new BufferedReader(new FileReader(file))) {
            EntityManagerFactory emf = Persistence.createEntityManagerFactory("TugasPert12PU");
            Depokeretasbi ctrl = new Depokeretasbi(emf);

            String line;
            br.readLine(); // skip header
            while ((line = br.readLine()) != null) {
                String[] data = line.split(",");
                Depokeretasbi d = new Depokeretasbi();
                d.setNomorArmada(data[0]);
                d.setJenisArmada(data[1]);
                d.setTanggalMulaiDinas(java.sql.Date.valueOf(data[2]));
                ctrl.create(d);
            }

            JOptionPane.showMessageDialog(this, "CSV berhasil diunggah!");
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Gagal unggah: " + e.getMessage());
        }
    }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        Connection conn = null;
        try {
            String url = "jdbc:postgresql://localhost:5432/pbo_pert7";
            String user = "postgres";
            String pass = "ABCDE12345";
            conn = DriverManager.getConnection(url, user, pass);
            
            String[] options = {"Depo Saja", "Perawatan Saja", "Keduanya"};
            int choice = JOptionPane.showOptionDialog(
                    this,
                    "Pilih laporan yang ingin dicetak:",
                    "Opsi Cetak Laporan",
                    JOptionPane.DEFAULT_OPTION,
                    JOptionPane.QUESTION_MESSAGE,
                    null,
                    options,
                    options[2]
            );
            
            if (choice == -1) return;
            
            JasperReport jasperReport;
            JasperPrint jasperPrint;
            
            switch (choice) {
                case 0: // Depo saja
                    jasperReport = JasperCompileManager.compileReport("src/tugaspert12/DepoSBI.jrxml");
                    jasperPrint = JasperFillManager.fillReport(jasperReport, null, conn);
                    JasperViewer.viewReport(jasperPrint, false);
                    break;
                case 1: // Perawatan saja
                    jasperReport = JasperCompileManager.compileReport("src/tugaspert12/Perawatan.jrxml");
                    jasperPrint = JasperFillManager.fillReport(jasperReport, null, conn);
                    JasperViewer.viewReport(jasperPrint, false);
                    break;
                case 2: // Keduanya
                    // Cetak Depo
                    jasperReport = JasperCompileManager.compileReport("src/tugaspert12/DepoSBI.jrxml");
                    jasperPrint = JasperFillManager.fillReport(jasperReport, null, conn);
                    JasperViewer.viewReport(jasperPrint, false);

                    // Cetak Perawatan
                    jasperReport = JasperCompileManager.compileReport("src/tugaspert12/Perawatan.jrxml");
                    jasperPrint = JasperFillManager.fillReport(jasperReport, null, conn);
                    JasperViewer.viewReport(jasperPrint, false);
                    
                    break;
            }
        
        } catch (SQLException | JRException e) {
            JOptionPane.showMessageDialog(this, "❌ Gagal mencetak laporan: " + e.getMessage());
            e.printStackTrace();
        } finally {
            try {
                if (conn != null) conn.close();
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        try {
        JFileChooser chooser = new JFileChooser();
        chooser.setDialogTitle("Simpan CSV");
        int userSelection = chooser.showSaveDialog(this);

        if (userSelection == JFileChooser.APPROVE_OPTION) {
            File fileToSave = chooser.getSelectedFile();
            if (!fileToSave.getName().toLowerCase().endsWith(".csv")) {
                fileToSave = new File(fileToSave.getAbsolutePath() + ".csv");
            }

            // Pilihan tabel untuk di-download
            String[] options = {"Depo", "Perawatan", "Keduanya"};
            int choice = JOptionPane.showOptionDialog(
                    this,
                    "Pilih tabel yang ingin diunduh:",
                    "Download CSV",
                    JOptionPane.DEFAULT_OPTION,
                    JOptionPane.QUESTION_MESSAGE,
                    null,
                    options,
                    options[2]
            );

            if (choice == -1) return; // batal

            try (java.io.PrintWriter pw = new java.io.PrintWriter(fileToSave)) {
                if (choice == 0 || choice == 2) { // Depo
                    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                    // header
                    for (int i = 0; i < model.getColumnCount(); i++) {
                        pw.print(model.getColumnName(i));
                        if (i != model.getColumnCount() - 1) pw.print(",");
                    }
                    pw.println();
                    // data
                    for (int i = 0; i < model.getRowCount(); i++) {
                        for (int j = 0; j < model.getColumnCount(); j++) {
                            pw.print(model.getValueAt(i, j));
                            if (j != model.getColumnCount() - 1) pw.print(",");
                        }
                        pw.println();
                    }
                }

                if (choice == 1 || choice == 2) { // Perawatan
                    DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
                    // tambahkan baris kosong untuk pisah tabel jika keduanya
                    if (choice == 2) pw.println();
                    // header
                    for (int i = 0; i < model.getColumnCount(); i++) {
                        pw.print(model.getColumnName(i));
                        if (i != model.getColumnCount() - 1) pw.print(",");
                    }
                    pw.println();
                    // data
                    for (int i = 0; i < model.getRowCount(); i++) {
                        for (int j = 0; j < model.getColumnCount(); j++) {
                            pw.print(model.getValueAt(i, j));
                            if (j != model.getColumnCount() - 1) pw.print(",");
                        }
                        pw.println();
                    }
                }
            }

            JOptionPane.showMessageDialog(this, "✅ File CSV berhasil disimpan di: " + fileToSave.getAbsolutePath());

        }
    } catch (Exception ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this, "❌ Gagal menyimpan CSV: " + ex.getMessage());
    }
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIMainClass12.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIMainClass12.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIMainClass12.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIMainClass12.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIMainClass12().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
